### ISSUE TITLE
Issues with duqtools dash and merge

### ISSUE THREAD

**Issue by jcitrin** [duqtools/duqtools#379]
Hi guys. Sorry for the radio silence recently. 

I've been trying to run `duqtools dash` and `duqtools merge` on the test-scan we ran together a while ago.

I have the latest firefox loaded, and have pip installed streamlit. I've pulled the latest commit from the main branch. However I get the following error following `duqtools dash`

![image](https://user-images.githubusercontent.com/6648646/197806702-56353f42-e243-4522-b081-c2d50a1f39b8.png)

I also tried `duqtools merge` and get the following error. 
![image](https://user-images.githubusercontent.com/6648646/197808063-8ff9cc11-6818-48d0-86ce-67d166b4e91d.png)

I'm sure I'm doing something silly that's wrong. I am running these commands from the default directory (where duqtools.yaml and the run directories are). Any ideas what's up?

**Comment by stefsmeets** [comment]
Hi @jcitrin , the first error is fixed by updating `streamlit`: `pip install -U streamlit`

And for the second part, does your `duqtools.yaml` have a `merge` section? It looks something like this:

```
merge:
  data: runs.yaml
  template:
    db: jet
    run: 1
    shot: 94785
    user: docs
  output:
    db: jet
    run: 9999
    shot: 94785
  plan:
  - data_variables:
    - t_i_ave
    - zeff
    grid_variable: rho_tor_norm
    time_variable: time
```

Also check out the documentation for merging here: https://duqtools.readthedocs.io/en/latest/config/merge/

Otherwise, could you post your `duqtools.yaml` or the path to your config on gateway? Then I can have a better look.
