### ISSUE TITLE
Update python api to interface with global optimization codes

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#497]
I'm creating this issue to gather ideas of how we can update duqtools to make it easy to interface with from other codes. For example, writing objective functions for global optimization algorithms. Duqtools can act as an interface between high-level python code and jintrac and handle creating the required input files and data for jintrac.

I think the goal for this interface should be to have a function to create a single run from python directly.

```python
from duqtools.api import create

config = {...}

task = create(config)
task.set_output_directory('./output')
task.run()
```

We should be able to specify the output directory somewhere on `task` (default '.').

`config` can be something that looks like the `duqtools.yaml` config, but with a slightly modified schema. Most of it is the same, but it it takes `operations` (essentially a list of [`IDSOperation`](https://github.com/duqtools/duqtools/blob/36bf9e89c75d312a905dd11d36f460ec5aeffd61/src/duqtools/schema/_dimensions.py#L100) and [`JettoOperation`](https://github.com/duqtools/duqtools/blob/36bf9e89c75d312a905dd11d36f460ec5aeffd61/src/duqtools/schema/_dimensions.py#L129)) instead of `dimensions` and `matrix`.

Something like this:

```yaml
create:
  run_dir: /afs/eufus.eu/user/g/username/jetto_runs/run_1
  template: /pfs/work/username/jetto/runs/duqtools_template
  template_data:
    user: test
    db: jet
    shot: 1234
    run: 1
  operations:
  - operator: multiply
    values: 1.1
    variable: t_i_ave
  - operator: multiply
    value: 1.3
    variable: zeff
  - operator: copyto
    value: 296.0
    variable: major_radius
system: jetto
```
