### ISSUE TITLE
Make IDS look-ups configurable

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#501]
This issue contains some follow-up from #494 

The goal is to make the IDS variable definition configurable through some yaml file (like `variables.yaml`).

- [x] I want to be able to define IDS lookups in some file like `variables.yaml` as well, so that they can be more easily configured. Perhaps we can tap into the same system. I'm not quite sure yet what this would look like.
- [x] This listing needs to be able to search several IDS paths until it finds some number that is not None and is not some enormous number (some IDS values default to `-9e+40`?).
- [x] Also needs a default value to fall back to (currently it crashes).
- [x] In IDSMapping, can we support this syntax:

```python
e = handle.get('equilibrium')
# Current:
b0 = e['vacuum_toroidal_field/b0'][0]
# Desired:
b0 = e['vacuum_toroidal_field/b0/0']
```

This will make it simpler to define the path to a IDS variable in a config. -> #500 

### Proposal

```yaml
- name: t_start
  type: IDS2jetto-variable
  paths:
    - ids: equilibrium
      path: time/0
  default: None  # raise if None

- name: b_field
  type: IDS2jetto-variable
  paths:
    - ids: equilibrium
      path: vacuum_toroidal_field/b0/0
    - ids: equilibrium
      path: time_slice/0/global_quantities/magnetic_axis/b_field_tor/0
  accept_if:
    - [ne, 0]
    - [lt, 1e40]
  default: None  # raise if None

- name: major_radius
  type: IDS2jetto-variable
  paths:
    - ids: equilibrium
      path: vacuum_toroidal_field/r0
    - ids: equilibrium
      path: time_slice/0/global_quantities/magnetic_axis/r
  accept_if:
    - [ne, 0]
    - [lt, 1e40]
  default: None  # raise if None
```
