### ISSUE TITLE
Add `duqtools setup` to grab values from data for single run

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#515]
It may be useful to make the single run equivalent of `duqduq setup` to make use of the IDS to jetto conversions implemented in #494 #502. 

We can reuse the code from and make the CLI should be compatible with `duqduq setup`.

Run with:

```bash
duqtools setup --handle user/db/123/456 --run_name my_run --template duqtools.template.yaml
# -> creates duqtools.yaml
```

### Example `duqtools.template.yaml`:

```yaml
create:
  runs_dir: /afs/eufus.eu/user/g/g2ssmee/jetto_runs/duqduq/{{ run.name }}
  template: /pfs/work/g2aho/jetto/runs/runparallel/jet90350/interpretive_esco02/
  template_data:
    user: {{ handle.user }}
    db: {{ handle.db }}
    shot: {{ handle.shot }}
    run: {{ handle.run }}
  sampler:
    method: latin-hypercube
    n_samples: 25
  dimensions:
    - variable: zeff
      operator: multiply
      values: [0.8, 0.9, 1.0, 1.1, 1.2]
    - variable: t_e
      operator: multiply
      values: [0.8, 0.9, 1.0, 1.1, 1.2]
    - variable: major_radius
      operator: copyto
      values: [ {{ variables.major_radius | round(4) }} ]
    - variable: b_field
      operator: copyto
      values: [ {{ variables.b_field | round(4) }} ]
    - variable: t_start
      operator: copyto
      values: [ {{ variables.t_start | round(4) }} ]
    - variable: t_end
      operator: copyto
      values: [ {{ (variables.t_start + 0.01) | round(4) }} ]
system: jetto-v220922
```
