### ISSUE TITLE
Generate base run for duqduq create

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#565]
Take the template data,
do not modify any variables in the IDS (essentially skip `DimVariables`),
call the run `base`.

output:
```
data_1/base
data_1/run_0000
data_1/run_0001
data_1/run_000n
```

Add an option to just run base run (ignore variables).

`duqduq create --base` --> just create base runs
`duqtools create --base` -> just create base run

**Comment by stefsmeets** [comment]
Once a base has been generated, use that as the template for the actual UQ run. The duqtools.yaml will then look something like this:

```yaml
create:
  runs_dir: /pfs/work/username/jetto_runs/duqduq/{{ run.name }}
  template: /pfs/work/username/jetto/runs/path/to/base
  sampler:
    method: latin-hypercube
    n_samples: 3
  dimensions:
    - variable: zeff
      operator: add
      values: [0.01, 0.02, 0.03]
    - variable: t_e
      operator: multiply
      values: [0.8, 1.0, 1.2]
system: jetto
```

`template_data` is pulled from the template, and we do not need to update the jetto.jset from the IDS variables anymore.

**Comment by stefsmeets** [comment]
This is now possible using 2 templates:

```
# base run
```yaml
create:
  runs_dir: /pfs/work/username/jetto_runs/duqduq/{{ run.name }}
  template: /pfs/work/username/jetto/runs/path/to/template
  operations:
     ...
  sampler:
    method: latin-hypercube
    n_samples: 3
  dimensions:
    ...
system: jetto
```

Run:

```
duqduq setup
duqduq create --base
duqduq submit
```

UQ runs:

```
# UQ run
```yaml
create:
  runs_dir: /pfs/work/username/jetto_runs/duqduq/{{ run.name }}
  template: /pfs/work/username/jetto/runs/duqduq/{{ run.name }}/base
  operations:
     ...
  sampler:
    method: latin-hypercube
    n_samples: 3
  dimensions:
    ...
system: jetto
```

Run:

```
duqduq setup
duqduq create
duqduq submit
```
