### ISSUE TITLE
Add a *no-system* system

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#637]
I was thinking that we should be able to specify no system at all:

```yaml
create:
  template: None
system:
  name: None
```

This works without a template, and only `template_data`. This would just convert the data and setup the imas data.
