### ISSUE TITLE
Duqtools Operations, add `input_variables` to `operation: custom`

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#674]
- [x] Jetto Variables do not support operations, (only `copy_to`) so this needs to be implemented as well
- [x] Operations should have a central place, as the data wrangling from an operation should be similar for any variable type
- [x] Implement the `input_variables` in an operation
  - [x] For IDS
    - [x] With IDS input_variables
    - [x] With Jetto Input_variables 
  - [x]  For Jetto
    - [x] With IDS input_variables
    - [x] With Jetto Input_variables 
- [ ] Allow for multidimensional IDS data? This one is tricky, as the apply procedures for Jetto and IDS differ at this point (Jetto has no notion of dimension) and we do want to combine them. So it is probably better to restrict input variables to a single "dimension" (no `*` allowed in the ids variable path). 
- [x] Documentation
- [x] Tests
- [x] Convert input_variables from `dict` to `namespace`
- [x] update tests
- [x] update docs

It seemed better to integrate with the custom operation type, as it naturally builds upon that. Otherwise many checks would have to be implemented for both

```yaml
variable: jetto_variable
operator: custom
input_variables:
  - "t_e"
  - "t_i_ave"
value: 2.0
custom: 'np.mean(var.t_e / var.t_i_ave + data / value)'
```
