### ISSUE TITLE
jintrac.launch missing during the job submission

### ISSUE THREAD

**Issue by EnzoVergnaud** [duqtools/duqtools#735]
Hello,

I tried to submit a job on JINTRAC version 31.0.0 but I crashed with this ll.out file:

```
Failed to find expected JINTRAC launchfile at /gss_efgw_work/work/g2evergn/jetto/runs/run57757duqtools/run_0000/jintrac.launch
```

The problematic part of the script that I used: (the new_submit_script is a .llcmd personalized to correspond to an existing reference run)

```
new_submit_script = """#!/bin/sh
#SBATCH -J duqtools.data_01.run_0000
#SBATCH -D /pfs/work/g2evergn/jetto/runs/run57757duqtools/run_0000
#SBATCH -i /dev/null
#SBATCH -o ll.out
#SBATCH -e ll.err
#SBATCH -p gw

#SBATCH -N 1
#SBATCH -n 48
#SBATCH -t 24:0:00
#SBATCH --mem=144G

cd /pfs/work/g2evergn/jetto/runs/run57757duqtools/run_0000
/gss_efgw_work/work/g2fjc/jintrac/31.0.0/python/bin/jintrac run
"""
with open(job.submit_script, "w") as f:
	f.writelines(new_submit_script)

job.submit()
```

The jintrac.launch of the reference run looks like this:

```
models:
  jetto:
    args: -S -I0 -p -xmpi -x64 run57757/run57757_currenddiff_heating_density_ids7_LHCD
      /gss_efgw_work/work/g2fjc/jintrac/31.0.0/jetto
    executable: /pfs/work/g2evergn/jetto/runs/run57757/run57757_currenddiff_heating_density_ids7_LHCD/rjettov
io: imas
imas:
  shot_out: 57757
  components:
  - IDSIN
  - JETTO
  - IDSOUT
  - HCD
  user_in: imasdb
  machine_in: west
  replace: false
  triggers: {
    }
  tend: 87.5
  machine_out: west
  run_out: 2
  tstart: 84.5
  intervals: {
    }
  run_in: 1
  user_out: imasdb
  shot_in: 57757
```
